### ISSUE TITLE
Issues with npm install

### ISSUE THREAD

**Issue by WildNomad** [MarshallOfSound/gpmdp-plugin-now-playing-text-file#2]
I'm a novice, so please forgive me if there is an obvious solution I'm overlooking.

I'm not sure if the same folder as the GPMDP exe is the right place for the contents of the gpmdp-plugin-now-playing-text-file-master folder, but that's where I put it. After getting Node.js so I could use the npm command and restarting GPMDP in developer mode, I entered npm install, as it states in the readme, I got these results in command prompt.

> C:\Users\user redacted\AppData\Local\GPMDP_3>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN gpmdp-plugin-now-playing-text-file@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
added 388 packages in 14.239s

I also attempted to run it in the console for GPMDP on the off-chance, but got an unexpected identifier error. Am I missing something obvious? Some tools or steps that are blatantly obvious to anybody who's slightly more experienced?

**Comment by MarshallOfSound** [comment]
@WildNomad This module doesn't work 👍 It is in a state where it worked with a version of GPMDP that was never released.  You can track plugin support here --> https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2216
